repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local
    hooks:
      - id: no-python-cache
        name: Prevent Python cache files
        entry: bash -c 'if find . -name "__pycache__" -type d -o -name "*.pyc" -o -name "*.pyo" | grep -q .; then echo "❌ Python cache files detected! Run: find . -name \"__pycache__\" -type d -exec rm -rf {} + && find . -name \"*.pyc\" -delete"; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
