version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 18
    commands:
      - pip install -r requirements-dev.txt

  build:
    commands:
      - npx cdk synth
      - pytest --junit-xml=test-results.xml tests/

reports:
  pytest_reports:
    files:
      - "test-results.xml"
    file-format: JUNITXML