AWSTemplateFormatVersion: '2010-09-09'
Description: |
  CloudFormation template for CodeBuild project for GitHub Actions runner instead of the GitHub Actions default. 
  Follow https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html#sample-github-action-runners-config to update GitHub Actions workflows to complete setup.

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub repository owner. If you have forked this project, then the owner is likely your GitHub Profile Name.
    Default: "aws-samples"
  GitHubRepository:
    Type: String
    Description: GitHub repository name
    Default: "sample-aws-security-incident-response-integrations"

Resources:
  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/codebuild/${AWS::StackName}
      RetentionInDays: 7
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: MinimalCodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                Resource: !Sub arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !GetAtt CodeBuildLogGroup.Arn
                  - !Sub ${CodeBuildLogGroup.Arn}:*
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource: '*'

  GitHubRunnerToken:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /github/runner/${GitHubOwner}/${GitHubRepository}/token
      Type: SecureString
      Value: !Ref GitHubToken
      Description: GitHub token for runner registration

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: github-actions-runner
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/amazonlinux-x86_64-standard:5.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: GITHUB_OWNER
            Value: !Ref GitHubOwner
          - Name: GITHUB_REPO
            Value: !Ref GitHubRepository
          - Name: GITHUB_TOKEN_PARAMETER
            Value: !Sub /github/runner/${GitHubOwner}/${GitHubRepository}/token
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepository}.git
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - echo "This is ignored in favor of the GitHub Actions Workflows"
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Sub /aws/codebuild/${AWS::StackName}
      TimeoutInMinutes: 480

Outputs:
  CodeBuildProjectName:
    Description: Name of the CodeBuild project
    Value: !Ref CodeBuildProject
